Transições sem botão e desenho da tela de Empréstimo em Detalhe
SteffanoP/projetoIP2 pull request #68
Opened 2021-07-04 11:42 UTC by hagafedra

## Descrição Rápida

Implementação da transição de telas de uma forma mais prática usando apenas dois cliques para que a tela de detalhes seja exibida. 

## Código

```java
    @FXML
    public void tblvOnMouseClicked(MouseEvent event) {
    	if (event.getButton().equals(MouseButton.PRIMARY) && event.getClickCount() >= 2)
	                    GerenciadorTelas.getInstance().changeScreen("telaDeDetalhes");
    }
```

2021-07-04 18:06 UTC, SteffanoP commented on src/gui/TelaBENSController.java
> +    }
A Tela de Bens ainda precisa ser configurada para a ação de Remover Bens. Sugiro abrir uma Issue para que outra pessoa possa trabalhar nisso.

2021-07-04 18:36 UTC, SteffanoP commented on src/gui/TelaDevedorDetalheController.java
> +    }
Não testei.

2021-07-04 19:06 UTC, SteffanoP requested changes
Só umas pequenas mudanças que achei necessário para a implementação final dessa Pull Request.

2021-07-04 19:06 UTC, SteffanoP commented on src/gui/TelaPrincipalAdmin.fxml
> +      <Button fx:id="btnSairPressed" layoutX="935.0" layoutY="46.0" mnemonicParsing="false" onAction="#btnSairPressed" text="Sair" />
Esse botão está duplicado com o botão de Voltar ao login, acho mais interessante remover o botão `Voltar ao login`.

2021-07-04 19:06 UTC, SteffanoP commented on src/gui/TelaFeedbackProposta.fxml
> +      <Button layoutX="911.0" layoutY="51.0" mnemonicParsing="false" text="Voltar" />
Esse botão está sem controle, acho interessante implementar a função de volta

2021-07-04 19:06 UTC, SteffanoP commented on src/gui/TelaAnaliseProposta.fxml
> +      <Button layoutX="725.0" layoutY="42.0" mnemonicParsing="false" text="Ver Detalhes do Cliente" />
Botão sem controle, é necessário criar uma função `onAction` para voltar para a tela anterior.

2021-07-04 19:06 UTC, SteffanoP commented on src/Main.java
> +        primaryStage.setTitle("Sistema de Gerenciamento de Empr�stimo Pessoal Alternativo");
Aqui você está mudando o encode para um formato aceito apenas em Windows (nesse caso `windows-1252`), seria interessante você manter o formato de encode `UTF-8`. Você deve procurar a função responsável por encode no Eclipse e ver se há a opção `UTF-8`.

2021-07-04 19:08 UTC, SteffanoP requested changes

2021-07-04 19:08 UTC, SteffanoP commented on src/gui/TelaPrincipalEmpregadoController.java
> +    	}
Tem que ter cuidado na seleção aqui para 2 cliques, pois o usuário pode selecionar um devedor protegido e apertar duas vezes em um devedor de alto risco e acabar indo para um devedor protegido por causa da ordem do `else if`.

2021-07-04 19:09 UTC, SteffanoP commented on src/gui/TelaPrincipalEmpregadoController.java
> +				SessionManager.getInstance().setClienteSessao((Cliente) Fachada.getInstance().buscarPessoa(email));
Achei **Genial** sua forma de implementação dentro do modelo, não testei mas é uma forma realmente interessante de pegar os dados do item selecionado. Parabéns!

2021-07-04 19:10 UTC, SteffanoP commented
@hagafedra já revisei, quando tu acordar dá uma olhada nos comentários que eu fiz, alguns eu pedi pra alteração, outros estou apenas comentando a situação.

2021-07-05 00:59 UTC, hagafedra commented on src/gui/TelaAnaliseProposta.fxml
> +      <Button layoutX="725.0" layoutY="42.0" mnemonicParsing="false" text="Ver Detalhes do Cliente" />
Tela ainda sem controlador.

2021-07-05 01:01 UTC, hagafedra commented on src/gui/TelaFeedbackProposta.fxml
> +      <Button layoutX="911.0" layoutY="51.0" mnemonicParsing="false" text="Voltar" />
Tela ainda sem controlador.

2021-07-05 01:10 UTC, hagafedra commented on src/gui/TelaPrincipalEmpregadoController.java
> +				SessionManager.getInstance().setClienteSessao((Cliente) Fachada.getInstance().buscarPessoa(email));
Muito obrigada!!

2021-07-05 01:20 UTC, hagafedra reviewed
@SteffanoP obrigada pela revisão, se puder checar se as mudanças estão corretas agradeceria muito!

2021-07-05 01:35 UTC, SteffanoP commented on src/gui/TelaAnaliseProposta.fxml
> +      <Button layoutX="725.0" layoutY="42.0" mnemonicParsing="false" text="Ver Detalhes do Cliente" />
Beleza, tou trabalhando nela.

2021-07-05 01:35 UTC, SteffanoP approved these changes
Tudo em ordem pode dar Merge!

2021-07-05 01:39 UTC, SteffanoP commented
@hagafedra corrigi os conflitos, você está livre para dar Merge!

2021-07-05 02:40 UTC, merged