Resolução dos issues relacionados às exceptions
SteffanoP/projetoIP2 pull request #69
Opened 2021-07-04 16:44 UTC by hagafedra

Closes: #30, #33, #34, #45, #51

2021-07-05 04:45 UTC, SteffanoP requested changes
Não consegui tudo, estou um pouco exausto hoje, mas tem algumas mudanças que quero que tu dê uma olhada @hagafedra.

2021-07-05 04:45 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +    public Map<LocalDate,Bens> listarBensCliente(long uidCliente) {
Creio que o encode esteja um pouco zuado

2021-07-05 04:45 UTC, SteffanoP commented on src/negocio/ControladorMovimentacao.java
> +     */
Também está com o encode zuado

2021-07-05 04:45 UTC, SteffanoP commented on src/negocio/ControladorProposta.java
> +    public Map<LocalDate, Proposta> listarPropostasCliente(long uidCliente) {
Se há a entrada com `uidCliente`, é necessário ter a exceção `PessoaInexistenteException`

2021-07-05 04:56 UTC, hagafedra commented on src/negocio/ControladorBENS.java
> +    public Map<LocalDate,Bens> listarBensCliente(long uidCliente) {
Vou dar uma olhada nisso

2021-07-05 13:57 UTC, SteffanoP requested changes

2021-07-05 13:57 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +            throw new BensDuplicadoException("Bens jÃ¡ registrado no sistema!");
@hagafedra  continua com vários erros de encode, lembra-te de usar o encode `UTF-8`. Aqui demonstra como: https://pt.stackoverflow.com/questions/248713/encoding-eclipse-intellij

2021-07-05 14:00 UTC, SteffanoP requested changes

2021-07-05 14:00 UTC, SteffanoP commented on src/negocio/ControladorProposta.java
>                  clienteExiste = true;
Erro de compilação aqui, sugiro você revisar essa Pull Request com testes.

2021-07-05 16:33 UTC, hagafedra commented on src/negocio/ControladorBENS.java
> +            throw new BensDuplicadoException("Bens jÃ¡ registrado no sistema!");
Obrigada!

2021-07-05 18:40 UTC, SteffanoP requested changes
Sinceramente, eu não sei porquê o teu Eclipse está assim :C

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +        }if(!existevalor)  throw new PessoaInexistenteException("Cliente NÃ£o existe!");
```suggestion
        }if(!existevalor)  throw new PessoaInexistenteException("Cliente Não existe!");
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +     * objetos do tipo {@code Bens} e ordenÃ¡-los a partir do seu atributo {@code dataCadastro}.
```suggestion
     * objetos do tipo {@code Bens} e ordená-los a partir do seu atributo {@code dataCadastro}.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +            throw new BensDuplicadoException("Bens jÃ¡ registrado no sistema!");
```suggestion
            throw new BensDuplicadoException("Bens já registrado no sistema!");
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +        if(!pendente)  throw new PessoaInexistenteException("Cliente NÃ£o existe!");
```suggestion
        if(!pendente)  throw new PessoaInexistenteException("Cliente Não existe!");
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +                    throw new BensInexistenteException("O bem nÃ£o existe!");
```suggestion
                    throw new BensInexistenteException("O bem não existe!");
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +     * @throws BensInexistenteException caso o bem a ser substituído nÃ£o exista no repositório.
```suggestion
     * @throws BensInexistenteException caso o bem a ser substituído não exista no repositório.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +            throw new BensInexistenteException("O bem nÃ£o existe!");
```suggestion
            throw new BensInexistenteException("O bem não existe!");
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorEmprestimo.java
> +     * M�todo que retorna todos os empr�stimos feitos pelo cliente identificado por seu {@code uid} atrav�s de um
```suggestion
     * Método que retorna todos os empréstimos feitos pelo cliente identificado por seu {@code uid} através de um 
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorEmprestimo.java
> +     * @param uidCliente se refere ao identificador �nico e exclusivo do cliente.
```suggestion
     * @param uidCliente se refere ao identificador único e exclusivo do cliente.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorEmprestimo.java
> +     * @return Map de empr�stimos ordenados por data.
```suggestion
     * @return Map de empréstimos ordenados por data.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorEmprestimo.java
> +     * {@code Emprestimo} que n�o pagaram at� o {@code prazo}.
```suggestion
     * Método que retorna um {@code Map} de {@code Emprestimo} ordenado por data referente ao {@code prazo} de todos os 
     * {@code Emprestimo} que não pagaram até o {@code prazo}.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorEmprestimo.java
> +     * {@code Emprestimo} que n�o foram pagos at� o {@code prazo}, por�m possuem um {@code score} alto.
```suggestion
     * Método que retorna um {@code Map} de {@code Emprestimo} ordenado por data referente ao {@code prazo} de todos os 
     * {@code Emprestimo} que não foram pagos até o {@code prazo}, porém possuem um {@code score} alto.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorEmprestimo.java
> +     * {@code Emprestimo} que n�o foram pagos at� o {@code prazo} e al�m disso possuem um {@code score} baixo.
```suggestion
     * Método que retorna um {@code Map} de {@code Emprestimo} ordenado por data referente ao {@code prazo} de todos os 
     * {@code Emprestimo} que não foram pagos até o {@code prazo} e além disso possuem um {@code score} baixo.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/ControladorMovimentacao.java
> +        }if(!moveClienteExiste)  throw new PessoaInexistenteException ("Cliente NÃ£o existe!");
```suggestion
        }if(!moveClienteExiste)  throw new PessoaInexistenteException ("Cliente Não existe!");
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * Mátodo que altera um bem por outro no repositório
```suggestion
     * Método que altera um bem por outro no repositório
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * @throws BensInexistenteException caso o bem a ser substituído nÃ£o exista no repositório.
```suggestion
     * @throws BensInexistenteException caso o bem a ser substituído não exista no repositório.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * MÃ©todo que remove bens do repositório.
```suggestion
     * Método que remove bens do repositório.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * @return uma {@code String} de dados, com base no mÃ©todo {@code toString()} do objeto {@code Emprestimo}.
```suggestion
     * @return uma {@code String} de dados, com base no método {@code toString()} do objeto {@code Emprestimo}.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * Método que lista todas as comissÃµes de empréstimos de que um empregado Ã© responsável.
```suggestion
     * Método que lista todas as comissões de empréstimos de que um empregado é responsável.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * @throws PessoaInexistenteException poderá acontecer caso o {@code email} nÃ£o esteja atribuído a nenhuma
```suggestion
     * @throws PessoaInexistenteException poderá acontecer caso o {@code email} não esteja atribuído a nenhuma
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * @return uma lista nÃ£o modificável do repositório de empregados.
```suggestion
     * @return uma lista não modificável do repositório de empregados.
```

2021-07-05 18:40 UTC, SteffanoP commented on src/negocio/SistemaEmprestimosBens.java
> +     * @throws PessoaInexistenteException poderÃ¡ acontecer caso o {@code uidCliente} nÃ£o esteja atribuído a nenhum cliente.
```suggestion
     * @throws PessoaInexistenteException poderá acontecer caso o {@code uidCliente} não esteja atribuído a nenhum cliente.
```

2021-07-05 19:21 UTC, hagafedra commented
> Sinceramente, eu não sei porquê o teu Eclipse está assim :C

Nem eu visse :((

2021-07-05 19:23 UTC, hagafedra commented on src/negocio/ControladorProposta.java
>                  clienteExiste = true;
Testado!

2021-07-06 00:10 UTC, SteffanoP requested changes

2021-07-06 00:10 UTC, SteffanoP commented on src/negocio/ControladorBENS.java
> +     * @param uidCliente se refere ao identificador Ãºnico e exclusivo do cliente.
```suggestion
     * @param uidCliente se refere ao identificador único e exclusivo do cliente.
```

2021-07-06 00:10 UTC, SteffanoP commented on src/negocio/ControladorProposta.java
>                  //Preencher mapa
Tanto para o método `listarContraProposta()` quanto para o método `listarPropostasCliente()` é necessário provar que o cliente existe, com a condição `proposta.getCliente().getUid() == uidCliente && proposta.isContraproposta()` isso não é possível caso o cliente tenha apenas propostas e vice-versa para o método `listarPropostasCliente()`.

2021-07-06 01:30 UTC, SteffanoP approved these changes

2021-07-06 01:31 UTC, merged